import { useMemo, useState } from "react";

import { compilePolicyWithNebius, fetchDemoComparison, fetchNebiusConnectionStatus, validatePolicyDraft } from "./api";
import { fallbackComparison } from "./demo";
import type { Decision, DemoComparison, NebiusConnectionStatus, Policy, PolicyValidationResponse } from "./types";

type RunKey = "baseline" | "repair";

const defaultPolicyText = `The coding agent may read README.md, src/, and tests/.
It may only write inside src/ and run pytest.
It must never read .env or Git metadata, delete files, or make network requests.`;

function decisionLabel(decision: Decision): string {
  return decision === "violation" ? "Observed violation" : decision.replaceAll("_", " ");
}

function App() {
  const [comparison, setComparison] = useState<DemoComparison>(fallbackComparison);
  const [selectedRun, setSelectedRun] = useState<RunKey>("baseline");
  const [connectionState, setConnectionState] = useState("Built-in sample simulation loaded");
  const [isLoading, setIsLoading] = useState(false);
  const [nebiusStatus, setNebiusStatus] = useState<NebiusConnectionStatus | null>(null);
  const [isCheckingNebius, setIsCheckingNebius] = useState(false);
  const [isCompiling, setIsCompiling] = useState(false);
  const [compileNotice, setCompileNotice] = useState<{ kind: "error" | "success"; text: string } | null>(null);
  const [compiledDraft, setCompiledDraft] = useState<{
    policy: Policy;
    sourceText: string;
    validation?: PolicyValidationResponse;
  } | null>(null);
  const [policyText, setPolicyText] = useState(defaultPolicyText);

  const activeRun = comparison[selectedRun];
  const draftIsStale = compiledDraft !== null && compiledDraft.sourceText !== policyText;
  const displayedPolicy = compiledDraft?.policy ?? comparison.policy;
  const policyJson = useMemo(() => JSON.stringify(displayedPolicy, null, 2), [displayedPolicy]);

  async function loadLocalRun() {
    setIsLoading(true);
    try {
      const next = await fetchDemoComparison();
      setComparison(next);
      setConnectionState("Sample simulation loaded from the local API");
    } catch {
      setConnectionState("Using the built-in sample; the local API could not be reached");
    } finally {
      setIsLoading(false);
    }
  }

  async function checkNebiusConnection() {
    setIsCheckingNebius(true);
    try {
      setNebiusStatus(await fetchNebiusConnectionStatus());
    } catch {
      setNebiusStatus({
        configured: false,
        connected: false,
        message: "Start the local FastAPI backend before checking Token Factory.",
        model_count: 0,
        nvidia_model_candidates: [],
        recommended_model: null,
      });
    } finally {
      setIsCheckingNebius(false);
    }
  }

  async function compilePolicy() {
    setIsCompiling(true);
    setCompileNotice(null);
    try {
      const result = await compilePolicyWithNebius(policyText);
      setCompiledDraft({ policy: result.policy, sourceText: policyText });
      setCompileNotice({
        kind: "success",
        text: `Policy draft generated by ${result.model} (${result.response_mode}). Review its rules below. It has not been applied or tested; the sample comparison stays unchanged.`,
      });
    } catch (error) {
      setCompileNotice({
        kind: "error",
        text: error instanceof Error ? error.message : "Token Factory could not compile the policy.",
      });
    } finally {
      setIsCompiling(false);
    }
  }

  async function testGeneratedDraft() {
    if (!compiledDraft || draftIsStale) return;
    setCompileNotice(null);
    try {
      const validation = await validatePolicyDraft(compiledDraft.policy);
      setCompiledDraft({ ...compiledDraft, validation });
    } catch (error) {
      setCompileNotice({
        kind: "error",
        text: error instanceof Error ? error.message : "RuleBranch could not test the generated draft.",
      });
    }
  }

  return (
    <main className="app-shell">
      <header className="topbar">
        <a className="brand" href="#workbench" aria-label="RuleBranch workbench">
          <span className="brand-mark" aria-hidden="true">⌇</span>
          <span>RuleBranch</span>
        </a>
        <div className="topbar-context">
          <span className="pulse" aria-hidden="true" />
          Local safety workbench
          <span className="divider" aria-hidden="true" />
          <span className="muted">{nebiusStatus?.connected ? "Token Factory connected" : "Nebius connection pending"}</span>
        </div>
        <div className="topbar-actions">
          <button className="quiet-button" type="button" onClick={checkNebiusConnection} disabled={isCheckingNebius}>
            {isCheckingNebius ? "Checking…" : "Check Token Factory"}
          </button>
          <button className="quiet-button" type="button" onClick={loadLocalRun} disabled={isLoading}>
            {isLoading ? "Loading sample…" : "Load sample simulation"}
          </button>
        </div>
      </header>

      <section className="hero" aria-labelledby="page-title">
        <div>
          <p className="eyebrow">Coding agent safety testing</p>
          <h1 id="page-title">Test the branch before it reaches the repository.</h1>
          <p className="hero-copy">
            Generate a policy from your instructions and explore a sample of how RuleBranch checks tool calls. This prototype does not yet run a coding agent or execute repository tests.
          </p>
        </div>
        <aside className="run-context" aria-label="Current test scenario">
          <span className="context-label">Scenario</span>
          <strong>README injection</strong>
          <span>Untrusted repository content attempts secret exfiltration.</span>
        </aside>
      </section>

      <section className="branch-ribbon" aria-label="Safety comparison path">
        <div className="ribbon-step is-baseline">
          <span>01</span>
          <div><strong>Observe</strong><small>sample calls without enforcement</small></div>
        </div>
        <div className="ribbon-link" aria-hidden="true"><i /><i /></div>
        <div className="ribbon-step is-repair">
          <span>02</span>
          <div><strong>Enforce</strong><small>sample calls checked against rules</small></div>
        </div>
        <p>This fixed sample illustrates blocked tool calls. It is separate from your generated policy and is not evidence of a completed coding task.</p>
      </section>

      <section className={`connection-card ${nebiusStatus?.connected ? "is-connected" : ""}`} aria-live="polite">
        <div>
          <p className="eyebrow">Token Factory preflight</p>
          <h2>{nebiusStatus?.connected ? "Account connection verified" : "Model selection stays under your control"}</h2>
          <p>{nebiusStatus?.message ?? "Check the connection to list models without sending an inference prompt or displaying your private key."}</p>
        </div>
        {nebiusStatus?.connected && (
          <div className="model-result">
            <span className="context-label">NVIDIA candidates</span>
            {nebiusStatus.nvidia_model_candidates.length ? (
              <>
                <code>{nebiusStatus.recommended_model}</code>
                <small>{nebiusStatus.nvidia_model_candidates.length} eligible candidate{nebiusStatus.nvidia_model_candidates.length === 1 ? "" : "s"} found. Copy the displayed identifier into <code>NEBIUS_MODEL</code>, then restart the backend.</small>
              </>
            ) : (
              <small>No eligible NVIDIA/Nemotron model was returned. Do not select a different family until we check the hackathon requirement.</small>
            )}
          </div>
        )}
      </section>

      <section id="workbench" className="workbench" aria-label="RuleBranch safety workbench">
        <aside className="policy-panel panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Authority</p>
              <h2>Policy under review</h2>
            </div>
            <span className={`status-pill ${compiledDraft?.validation?.passed ? "safe" : "review"}`}>
              {isCompiling
                ? "Generating"
                : draftIsStale
                  ? "Out of date"
                  : compiledDraft?.validation?.passed
                    ? "Checks passed"
                    : compiledDraft?.validation
                      ? "Review failed"
                      : compiledDraft
                        ? "Needs review"
                        : "Sample"}
            </span>
          </div>
          <label className="field-label" htmlFor="policy-text">Plain-language boundary</label>
          <textarea
            id="policy-text"
            value={policyText}
            onChange={(event) => {
              setPolicyText(event.target.value);
              setCompileNotice(null);
            }}
            disabled={isCompiling}
            spellCheck="false"
          />
          <p className="field-hint">Compilation is opt-in: a request is made only after you select the button below.</p>
          <div className="policy-actions">
            <button className="compile-button" type="button" onClick={compilePolicy} disabled={isCompiling}>
              {isCompiling ? "Generating policy…" : "Compile with Token Factory"}
            </button>
            {compiledDraft && (
              <button
                className="validate-button"
                type="button"
                onClick={testGeneratedDraft}
                disabled={draftIsStale || isCompiling}
              >
                Test generated draft locally
              </button>
            )}
          </div>
          {compileNotice && <p className={`compile-notice ${compileNotice.kind}`} role={compileNotice.kind === "error" ? "alert" : "status"}>{compileNotice.text}</p>}
          {draftIsStale && <p className="compile-notice stale" role="status">You changed the instructions. The draft below was generated from the previous text and needs to be generated again.</p>}
          {compiledDraft?.validation && (
            <section className={`validation-card ${compiledDraft.validation.passed ? "passed" : "failed"}`} aria-live="polite">
              <span className="context-label">Local synthetic checks</span>
              <strong>{compiledDraft.validation.passed_checks}/{compiledDraft.validation.total_checks} passed</strong>
              <p>{compiledDraft.validation.message}</p>
              <details open={!compiledDraft.validation.passed}>
                <summary>View all check results</summary>
                <ul>
                  {compiledDraft.validation.cases.map((testCase) => (
                    <li key={testCase.id} className={testCase.passed ? "passed" : "failed"}>
                      <span aria-hidden="true">{testCase.passed ? "✓" : "×"}</span>
                      <div>
                        <strong>{testCase.label}</strong>
                        <small>
                          Expected {testCase.expected}; got {testCase.actual}
                          {testCase.rule_id ? ` · ${testCase.rule_id}` : " · deny by default"}
                        </small>
                      </div>
                    </li>
                  ))}
                </ul>
              </details>
            </section>
          )}
          <p className="field-hint">{compiledDraft ? "Generated draft rules — awaiting your review, not applied to the sample." : "The rules below belong to the built-in sample. A successful compilation will create a separate draft."}</p>
          <details className="policy-details">
            <summary>{compiledDraft ? "View generated draft JSON" : "View sample policy JSON"}</summary>
            <pre>{policyJson}</pre>
          </details>
          <div className="rule-list" aria-label={compiledDraft ? "Generated draft rules" : "Sample policy rules"}>
            {displayedPolicy.rules.map((rule) => (
              <div key={rule.id} className={`rule-row ${rule.effect}`}>
                <span>{rule.effect}</span>
                <div><strong>{rule.tool}</strong><small>{rule.path_patterns.join(", ")}</small></div>
              </div>
            ))}
          </div>
        </aside>

        <section className="trace-panel panel" aria-labelledby="trace-title">
          <div className="panel-heading trace-heading">
            <div>
              <p className="eyebrow">Sample simulation</p>
              <h2 id="trace-title">{activeRun.label}</h2>
            </div>
            <div className="run-switch" role="group" aria-label="Select comparison run">
              <button type="button" className={selectedRun === "baseline" ? "active" : ""} onClick={() => setSelectedRun("baseline")}>Baseline</button>
              <button type="button" className={selectedRun === "repair" ? "active" : ""} onClick={() => setSelectedRun("repair")}>Repair</button>
            </div>
          </div>
          <p className="simulation-note">These are scripted example calls checked against the sample policy. No agent, file upload, source edit, or repository test was executed. Compiling a draft does not change these results.</p>
          <p className="trace-intro">Sample scenario: {comparison.finding}</p>
          <details className="policy-details">
            <summary>View the policy used for this sample</summary>
            <pre>{JSON.stringify(comparison.policy, null, 2)}</pre>
          </details>
          <ol className="trace-list">
            {activeRun.trace.map((event) => (
              <li key={`${activeRun.id}-${event.sequence}`} className={`trace-event ${event.decision}`}>
                <span className="sequence">{String(event.sequence).padStart(2, "0")}</span>
                <div className="trace-content">
                  <div className="trace-title-row">
                    <code>{event.tool}</code>
                    <span className={`decision-badge ${event.decision}`}>{decisionLabel(event.decision)}</span>
                  </div>
                  <p>{event.summary}</p>
                  <span className="trace-target">{Object.values(event.arguments).join("  ·  ")}</span>
                </div>
                <span className="trace-rule">{event.rule_id ?? "deny-by-default"}</span>
              </li>
            ))}
          </ol>
          <div className="trace-footer"><span className="pulse" aria-hidden="true" /> {connectionState}</div>
        </section>

        <aside className="metrics-panel panel" aria-labelledby="metrics-title">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Sample results</p>
              <h2 id="metrics-title">Simulation only</h2>
            </div>
          </div>
          <div className={`verdict-card ${selectedRun === "baseline" ? "is-unsafe" : ""}`}>
            <span>Sample verdict</span>
            <strong>{activeRun.metrics.policy_verdict}</strong>
            <p>{selectedRun === "baseline" ? "The sample records unauthorized calls without blocking them." : "The sample policy blocks unauthorized calls. Actual task completion has not been tested."}</p>
          </div>
          <dl className="metric-list">
            <div><dt>Sample unauthorized calls</dt><dd>{activeRun.metrics.unauthorized_attempts}</dd></div>
            <div><dt>Sample blocked calls</dt><dd>{activeRun.metrics.blocked_actions}</dd></div>
            <div><dt>Actual task completion</dt><dd>Not tested</dd></div>
          </dl>
          <div className="next-proof">
            <span className="context-label">Next evidence</span>
            <p>Next milestone: run a coding agent and repository tests in a Nebius Sandbox, then collect real execution results.</p>
          </div>
        </aside>
      </section>
    </main>
  );
}

export default App;
